; HEADER_BLOCK_START
; generated by OrcaSlicer 2.0.0 on 2024-05-23 at 10:01:32
; total layer number: 5
; filament_density: 1.27
; filament_diameter: 1.75
; max_z_height: 1.00
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 2624
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAHd0lEQVR4Ae3cvYokZRSA4Y4UlUVYF5
; UNjExMDEQTQTAQNHLBRBNBEMQL8AIm1AsQTIzNTQw39LJGSu2ld7Z7uqu6fs7P88ALYjjg4XyHanc7
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKOzBh9/fDO
; 0Aonrp8QefvvHlr08f//j37dDwz8O/2wFEMmxU+0F1N9sWEMZ9w8q2BYRwyaCybQGbmzKsDretHcDS
; 7h7Wr8kTEVjMNVuVJyKwmiWGlYM8MKslB5VtC5jNmsPKQR6YZItBdTdPROCsCMPKExE4a67PFeZ+It
; q2gGcibVW2LeCkDMPKtgXNZRpUti1oLPOwOty2dkBdc/4OMMrQ8kSEgipsVafyRIRCKg8r2xYU0WFQ
; 2baggI7D6nDb2gHxDc+iTMNlyTwRIbDOW9WpPBEhIMPqdA7yEIRBdXm2LdiQYTU+2xaszKC6PkMLVm
; BYzZcnIiyk2u8Ao+SJCDOzVS2fbQtmYFitl20LJjKotsu2BSMYVtvn94hwhsN6vDwR4QhbVdw8EeGA
; YRU/B3naM6jyZduiJcMqbw7ytGFQ1ckTkdIMq3p5IlKSzxXq5iBPGbaqPtm2SM2w6pdti3QMKtm2SM
; Gw0j6fPxCW3wHqWJ6IhGOr0rk8EQnBsNKl2bbYjEGlqdm2WJVhpWtzkGdxwzqf6T8Kxc8TkUXYqrRU
; nojMyucKWjoHea5mq9La2baYxLDSVtm2uJhBpSgZWtzLsFK0fP7AC/wOUJHzROQZW5Wy5CDfnGGlbN
; m2GjKolD3bVhOGlarkIF+Y3wGqap6IxdiqVD1PxCIMK3XJQT4xg0pds20lY1ipe7atBAwq6fkMraAM
; K+l4noiB+B2gdD5PxABsVdK4bFsbMaykadm2VmRQSfNk21qYYSXNm98jLsBhXVo2T8SZ2KqkdfJEvJ
; JhJa2bg/wEBpW0bbatCxlWUowc5O9hUEkx80S8w7CSYueJ+D+fK0g5an2Qt1VJOWu3bRlWUu5abFsG
; lVSrstuWYSXVrNTnD34HKNWvzBPxlXc/u3nzmz9S/fElTSv9E3EYWA8///n20ZPfbt/+7q9Uf3xJ40
; u9be0H1j5DS+pRym3r7sDab1uZ/vCSppXuIH9sYHkiSr1K80Q8NbD2OchLPUrxRDw3sGxbUp/CH+Qv
; GVi2LalXYbetMQPLQV7qU+hta8zQ8vmD1KewQ+vBRz88HTO0PBGlHpV6Itq2pPqVeiLatqQehd22xj
; 4RbVtSjxzkJaWrzLbliSj1KOzvER3kJZ3KQV5SqhzkJaXK5w+S0lVq28r0h5c0rTIHeZ8/SH3ye0RJ
; qfJ7REmpcpCXlC4HeUlpeuvbP29ffe/JzS4qB3lJQ4+++v329U9+un35nY9vdpE5yEu92w+rFANr4C
; Av9etwUKUaWHsO8lKPjg2rdANr4PeIUt2Gw/rDL345OqxSDqw925ZUq1NbVYmBNfD5g1SjS4ZV+oE1
; cJCX8nbpoCozsPZ8/iDlauyweu39r2P+XxymcpCX4jd2UJXarI5xkJdiNmVY7TpwkJdidd/nCu22ql
; PGblueiNK82apGcpCXtqn9YX0qnz9I6+WwPhMHeWnZPAFn5vMHaf7O/Q7QVnUlB3lpnmxVK3GQl66r
; 7c9rtuIgL43PVrUxB3npsnyuEISDvHS64bDuc4WAbFvS83kCBuf3iNJ/OawnMfYg7/MHVcpWlZTPH9
; Qth/XkfP6gDvkdYDEO8qqaJ2BRDvKqlN8BNuEgr+zZqppxkFfWfK7QlIO8MmWr4l8O8oqeYcVz/B5R
; EXNY5162LUXJVsVFfP6grXNYZxQHeW2RrYqr+PxBa+V3gMzCQV5L5neALMJBXnPnCciiHOQ1Vz5XYD
; Vjty1PRO2zVbEJB3mNzWGdTfn8QUsMKlsVi3KQl2FFKj5/0GF+B0gKDvKyVZGKzx8MK1sVqTjIG1S2
; KtLx+YNh5XMFUnGQr9lwWB+7VXkCkobPH+rkCUgLDvL587kC7fj8IV+2KlpzkK87rBzWKcnnD7UGlS
; cgLTjI1xhWO+jC5w8x8jtAGMFBfrtsVTCBg3z8YWWrggMO8jEHla0K7uEgH2dY+VwBLuAgP28O67AC
; 29b1eQLCivwecb1hZauCGYw9yHf//MFWBQH4/GH+YeWwDgvy+cM8g8oTEFbkIH/dsNoB6+p+kPe5Ai
; TU8SBvq4LEOh3kfa4ABVQ/yNuqoKCKB3nDCgqr8ntEh3VoJPO2ZauChjJ+/uCwDo1lOcjbqoBnIn/+
; 4HeAwAuiHeSHw/rYrcoTEJqJcJD3BAQutuVB3ucKwCRjt61rnoi2KuBqaxzkHdaB2Sz1+YP/wR6wmD
; kP8p6AwOKu/fzB7wCB1U05yNuqgM2M3bZsVcCmxhzkbVVACHMMLJ8rAKs590T0BATCGTuwdgBbOrZt
; 2aqAsO4e5G1VQHj7bcthHUhh2LY8AQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAKjuH2VsYAN9DDIIAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.40mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.40mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=square-BodyPad.stl_id_0_copy_0 CENTER=110,110 POLYGON=[[103,101],[117,101],[117,119],[103,119],[103,101]]
M73 P0 R2
;TYPE:Custom
M117 ; clear display for KAMP meshing
START_PRINT BED_TEMP=80 EXTRUDER_TEMP=255
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-5 F3600
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500 ACCEL_TO_DECEL=250
; printing object square-BodyPad.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=square-BodyPad.stl_id_0_copy_0
G1 Z.4 F9000
G1 X115.836 Y117.836
M73 P1 R2
G1 Z.4
G1 Z.2
G1 E5 F2400
;TYPE:Inner wall
;WIDTH:0.499999
G1 F900
G1 X104.164 Y117.836 E.42142
G1 X104.164 Y102.164 E.56584
M73 P2 R2
G1 X115.836 Y102.164 E.42142
M73 P3 R2
G1 X115.836 Y117.796 E.5644
M73 P4 R2
G1 X116.293 Y118.293 F9000
G1 F900
G1 X103.707 Y118.293 E.45442
G1 X103.707 Y101.707 E.59885
M73 P5 R2
G1 X116.293 Y101.707 E.45442
M73 P6 R2
G1 X116.293 Y118.253 E.5974
G1 X116.75 Y118.75 F9000
;TYPE:Outer wall
M73 P7 R2
G1 F900
G1 X103.25 Y118.75 E.48743
G1 X103.25 Y101.25 E.63185
M73 P8 R2
G1 X116.75 Y101.25 E.48743
M73 P9 R2
G1 X116.75 Y118.71 E.63041
M73 P10 R2
G1 E-3.5 F3600
;WIPE_START
G1 F900
G1 X115.75 Y118.713 E-1.5
;WIPE_END
G1 Z.6 F9000
G1 X115.69 Y103.247 Z.6
G1 Z.2
G1 E5 F2400
;TYPE:Bottom surface
;WIDTH:0.505984
G1 F1200
G1 X114.959 Y102.516 E.03781
G1 X114.304 Y102.516 E.02395
G1 X115.484 Y103.696 E.06105
G1 X115.484 Y104.351 E.02395
G1 X113.649 Y102.516 E.09493
G1 X112.994 Y102.516 E.02395
M73 P11 R2
G1 X115.484 Y105.006 E.1288
M73 P11 R1
G1 X115.484 Y105.661 E.02395
G1 X112.339 Y102.516 E.16268
G1 X111.684 Y102.516 E.02395
G1 X115.484 Y106.316 E.19656
G1 X115.484 Y106.971 E.02395
G1 X111.029 Y102.516 E.23043
G1 X110.374 Y102.516 E.02395
G1 X115.484 Y107.626 E.26431
M73 P12 R1
G1 X115.484 Y108.28 E.02395
G1 X109.72 Y102.516 E.29819
G1 X109.065 Y102.516 E.02395
G1 X115.484 Y108.935 E.33206
G1 X115.484 Y109.59 E.02395
G1 X108.41 Y102.516 E.36594
M73 P13 R1
G1 X107.755 Y102.516 E.02395
G1 X115.484 Y110.245 E.39982
G1 X115.484 Y110.9 E.02395
G1 X107.1 Y102.516 E.43369
M73 P14 R1
G1 X106.445 Y102.516 E.02395
G1 X115.484 Y111.555 E.46757
G1 X115.484 Y112.21 E.02395
G1 X105.79 Y102.516 E.50145
M73 P15 R1
G1 X105.136 Y102.516 E.02395
G1 X115.484 Y112.864 E.53532
G1 X115.484 Y113.519 E.02395
G1 X104.516 Y102.552 E.56737
M73 P16 R1
G1 X104.516 Y103.206 E.02395
G1 X115.484 Y114.174 E.56737
M73 P17 R1
G1 X115.484 Y114.829 E.02395
G1 X104.516 Y103.861 E.56737
G1 X104.516 Y104.516 E.02395
G1 X115.484 Y115.484 E.56737
M73 P18 R1
G1 X115.484 Y116.139 E.02395
G1 X104.516 Y105.171 E.56737
M73 P19 R1
G1 X104.516 Y105.826 E.02395
G1 X115.484 Y116.794 E.56737
G1 X115.484 Y117.449 E.02395
G1 X104.516 Y106.481 E.56737
M73 P20 R1
G1 X104.516 Y107.136 E.02395
G1 X114.864 Y117.484 E.53532
G1 X114.209 Y117.484 E.02395
G1 X104.516 Y107.791 E.50144
M73 P21 R1
G1 X104.516 Y108.445 E.02395
G1 X113.555 Y117.484 E.46756
G1 X112.9 Y117.484 E.02395
G1 X104.516 Y109.1 E.43369
M73 P22 R1
G1 X104.516 Y109.755 E.02395
G1 X112.245 Y117.484 E.39981
G1 X111.59 Y117.484 E.02395
G1 X104.516 Y110.41 E.36593
M73 P23 R1
G1 X104.516 Y111.065 E.02395
G1 X110.935 Y117.484 E.33206
G1 X110.28 Y117.484 E.02395
G1 X104.516 Y111.72 E.29818
G1 X104.516 Y112.375 E.02395
G1 X109.625 Y117.484 E.2643
M73 P24 R1
G1 X108.97 Y117.484 E.02395
G1 X104.516 Y113.03 E.23043
G1 X104.516 Y113.684 E.02395
G1 X108.316 Y117.484 E.19655
G1 X107.661 Y117.484 E.02395
G1 X104.516 Y114.339 E.16267
G1 X104.516 Y114.994 E.02395
M73 P25 R1
G1 X107.006 Y117.484 E.1288
G1 X106.351 Y117.484 E.02395
G1 X104.516 Y115.649 E.09492
G1 X104.516 Y116.304 E.02395
G1 X105.696 Y117.484 E.06104
G1 X105.041 Y117.484 E.02395
G1 X104.31 Y116.753 E.03781
; stop printing object square-BodyPad.stl id:0 copy 0
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
G92 E0

G1 E-3.5 F3600
;WIPE_START
G1 F1200
G1 X105.018 Y117.46 E-1.5
;WIPE_END
EXCLUDE_OBJECT_END NAME=square-BodyPad.stl_id_0_copy_0
;_SET_FAN_SPEED_CHANGING_LAYER
M140 S80 ; set bed temperature
; printing object square-BodyPad.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=square-BodyPad.stl_id_0_copy_0
G1 Z.6 F9000
G1 X116.011 Y118.011 Z.6
G1 Z.4
G1 E5 F2400
;TYPE:Inner wall
;WIDTH:0.449999
G1 X103.989 Y118.011 E.38657
M73 P26 R1
G1 X103.989 Y101.989 E.5152
G1 X116.011 Y101.989 E.38657
G1 X116.011 Y117.971 E.51391
M73 P27 R1
G1 X116.418 Y118.418 F9000
G1 F2400
G1 X103.582 Y118.418 E.41275
G1 X103.582 Y101.582 E.54138
G1 X116.418 Y101.582 E.41275
M73 P28 R1
G1 X116.418 Y118.378 E.54009
G1 X116.8 Y118.8 F9000
;TYPE:Outer wall
;WIDTH:0.399999
G1 F1500
G1 X103.2 Y118.8 E.38361
G1 X103.2 Y101.2 E.49644
M73 P29 R1
G1 X116.8 Y101.2 E.38361
G1 X116.8 Y118.76 E.49531
M73 P30 R1
G1 X115.157 Y117.883 F9000
;TYPE:Internal solid infill
;WIDTH:0.401766
G1 F2400
G1 X115.722 Y117.318 E.02265
G1 X115.722 Y116.811 E.01439
G1 X114.811 Y117.722 E.03655
G1 X114.303 Y117.722 E.01439
G1 X115.722 Y116.303 E.05689
G1 X115.722 Y115.796 E.01439
G1 X113.796 Y117.722 E.07724
G1 X113.288 Y117.722 E.01439
G1 X115.722 Y115.288 E.09758
G1 X115.722 Y114.781 E.01439
G1 X112.781 Y117.722 E.11792
M73 P31 R1
G1 X112.273 Y117.722 E.01439
G1 X115.722 Y114.273 E.13827
G1 X115.722 Y113.766 E.01439
G1 X111.766 Y117.722 E.15861
G1 X111.258 Y117.722 E.01439
G1 X115.722 Y113.258 E.17896
G1 X115.722 Y112.751 E.01439
G1 X110.751 Y117.722 E.1993
G1 X110.243 Y117.722 E.01439
G1 X115.722 Y112.243 E.21964
G1 X115.722 Y111.736 E.01439
M73 P32 R1
G1 X109.736 Y117.722 E.23999
G1 X109.228 Y117.722 E.01439
G1 X115.722 Y111.228 E.26033
G1 X115.722 Y110.721 E.01439
G1 X108.721 Y117.722 E.28067
G1 X108.213 Y117.722 E.01439
G1 X115.722 Y110.213 E.30102
G1 X115.722 Y109.706 E.01439
G1 X107.706 Y117.722 E.32136
M73 P33 R1
G1 X107.198 Y117.722 E.01439
G1 X115.722 Y109.198 E.34171
G1 X115.722 Y108.691 E.01439
G1 X106.691 Y117.722 E.36205
G1 X106.183 Y117.722 E.01439
G1 X115.722 Y108.183 E.38239
M73 P34 R1
G1 X115.722 Y107.676 E.01439
G1 X105.676 Y117.722 E.40274
G1 X105.168 Y117.722 E.01439
G1 X115.722 Y107.168 E.42308
G1 X115.722 Y106.661 E.01439
G1 X104.661 Y117.722 E.44343
M73 P35 R1
G1 X104.278 Y117.722 E.01087
G1 X104.278 Y117.598 E.00352
G1 X115.722 Y106.154 E.45879
G1 X115.722 Y105.646 E.01439
G1 X104.278 Y117.091 E.45879
G1 X104.278 Y116.583 E.01439
G1 X115.722 Y105.139 E.45879
M73 P36 R1
G1 X115.722 Y104.631 E.01439
G1 X104.278 Y116.076 E.45879
G1 X104.278 Y115.568 E.01439
G1 X115.722 Y104.124 E.45879
G1 X115.722 Y103.616 E.01439
G1 X104.278 Y115.061 E.45879
M73 P37 R1
G1 X104.278 Y114.553 E.01439
G1 X115.722 Y103.109 E.45879
G1 X115.722 Y102.601 E.01439
G1 X104.278 Y114.046 E.45879
M73 P38 R1
G1 X104.278 Y113.538 E.01439
G1 X115.538 Y102.278 E.45142
G1 X115.031 Y102.278 E.01439
G1 X104.278 Y113.031 E.43108
G1 X104.278 Y112.523 E.01439
G1 X114.523 Y102.278 E.41073
M73 P39 R1
G1 X114.016 Y102.278 E.01439
G1 X104.278 Y112.016 E.39039
G1 X104.278 Y111.508 E.01439
G1 X113.508 Y102.278 E.37004
G1 X113.001 Y102.278 E.01439
G1 X104.278 Y111.001 E.3497
G1 X104.278 Y110.494 E.01439
G1 X112.494 Y102.278 E.32936
M73 P40 R1
G1 X111.986 Y102.278 E.01439
G1 X104.278 Y109.986 E.30901
G1 X104.278 Y109.479 E.01439
G1 X111.479 Y102.278 E.28867
G1 X110.971 Y102.278 E.01439
G1 X104.278 Y108.971 E.26832
G1 X104.278 Y108.464 E.01439
M73 P41 R1
G1 X110.464 Y102.278 E.24798
G1 X109.956 Y102.278 E.01439
G1 X104.278 Y107.956 E.22764
G1 X104.278 Y107.449 E.01439
G1 X109.449 Y102.278 E.20729
G1 X108.941 Y102.278 E.01439
G1 X104.278 Y106.941 E.18695
G1 X104.278 Y106.434 E.01439
G1 X108.434 Y102.278 E.16661
G1 X107.926 Y102.278 E.01439
M73 P42 R1
G1 X104.278 Y105.926 E.14626
G1 X104.278 Y105.419 E.01439
G1 X107.419 Y102.278 E.12592
G1 X106.911 Y102.278 E.01439
G1 X104.278 Y104.911 E.10557
G1 X104.278 Y104.404 E.01439
G1 X106.404 Y102.278 E.08523
G1 X105.896 Y102.278 E.01439
G1 X104.278 Y103.896 E.06489
G1 X104.278 Y103.389 E.01439
G1 X105.389 Y102.278 E.04454
G1 X104.881 Y102.278 E.01439
G1 X104.117 Y103.042 E.03064
G1 X115.744 Y102.416 F9000
;TYPE:Gap infill
;WIDTH:0.114511
G1 F1800
G1 X115.778 Y102.308 E.00064
G1 X115.755 Y102.193 E.00067
M73 P43 R1
G1 X104.381 Y102.323 F9000
;TYPE:Internal solid infill
;WIDTH:0.38292
G1 F2400
G1 X104.317 Y102.36 E.00198
G1 X104.382 Y102.394 E.00198
; stop printing object square-BodyPad.stl id:0 copy 0
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.6
G92 E0

G1 E-4.7791 F3600
;WIPE_START
G1 F2400
G1 X104.317 Y102.36 E-.11048
G1 X104.381 Y102.323 E-.11042
;WIPE_END
EXCLUDE_OBJECT_END NAME=square-BodyPad.stl_id_0_copy_0
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object square-BodyPad.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=square-BodyPad.stl_id_0_copy_0
G1 Z.8 F9000
G1 X116.011 Y118.011 Z.8
G1 Z.6
G1 E5 F2400
;TYPE:Inner wall
;WIDTH:0.449999
G1 X103.989 Y118.011 E.38657
M73 P44 R1
G1 X103.989 Y101.989 E.5152
G1 X116.011 Y101.989 E.38657
G1 X116.011 Y117.971 E.51391
M73 P45 R1
G1 X116.418 Y118.418 F9000
G1 F2400
G1 X103.582 Y118.418 E.41275
G1 X103.582 Y101.582 E.54138
G1 X116.418 Y101.582 E.41275
G1 X116.418 Y118.378 E.54009
M73 P46 R1
G1 X116.8 Y118.8 F9000
;TYPE:Outer wall
;WIDTH:0.399999
G1 F1500
G1 X103.2 Y118.8 E.38361
G1 X103.2 Y101.2 E.49644
M73 P47 R1
G1 X116.8 Y101.2 E.38361
G1 X116.8 Y118.76 E.49531
M73 P48 R1
G1 E-3.5 F3600
;WIPE_START
G1 F1500
G1 X115.8 Y118.763 E-1.5
;WIPE_END
G1 Z1 F9000
G1 X104.381 Y117.603 Z1
G1 Z.6
G1 E5 F2400
;TYPE:Internal solid infill
;WIDTH:0.38292
G1 X104.317 Y117.64 E.00198
G1 X104.382 Y117.675 E.00198
G1 X115.883 Y102.843 F9000
;WIDTH:0.401766
M73 P49 R1
G1 F2400
G1 X115.318 Y102.278 E.02265
G1 X114.811 Y102.278 E.01439
G1 X115.722 Y103.189 E.03655
G1 X115.722 Y103.697 E.01439
G1 X114.303 Y102.278 E.05689
G1 X113.796 Y102.278 E.01439
G1 X115.722 Y104.204 E.07724
G1 X115.722 Y104.712 E.01439
G1 X113.288 Y102.278 E.09758
G1 X112.781 Y102.278 E.01439
G1 X115.722 Y105.219 E.11792
G1 X115.722 Y105.727 E.01439
G1 X112.273 Y102.278 E.13827
G1 X111.766 Y102.278 E.01439
G1 X115.722 Y106.234 E.15861
G1 X115.722 Y106.742 E.01439
G1 X111.258 Y102.278 E.17896
M73 P50 R1
G1 X110.751 Y102.278 E.01439
G1 X115.722 Y107.249 E.1993
G1 X115.722 Y107.757 E.01439
G1 X110.243 Y102.278 E.21964
G1 X109.736 Y102.278 E.01439
G1 X115.722 Y108.264 E.23999
G1 X115.722 Y108.772 E.01439
G1 X109.228 Y102.278 E.26033
G1 X108.721 Y102.278 E.01439
M73 P51 R1
G1 X115.722 Y109.279 E.28067
G1 X115.722 Y109.787 E.01439
G1 X108.213 Y102.278 E.30102
G1 X107.706 Y102.278 E.01439
G1 X115.722 Y110.294 E.32136
G1 X115.722 Y110.802 E.01439
G1 X107.198 Y102.278 E.34171
M73 P52 R1
G1 X106.691 Y102.278 E.01439
G1 X115.722 Y111.309 E.36205
G1 X115.722 Y111.817 E.01439
G1 X106.183 Y102.278 E.38239
G1 X105.676 Y102.278 E.01439
G1 X115.722 Y112.324 E.40274
G1 X115.722 Y112.832 E.01439
M73 P53 R1
G1 X105.168 Y102.278 E.42308
G1 X104.661 Y102.278 E.01439
G1 X115.722 Y113.339 E.44343
G1 X115.722 Y113.846 E.01439
G1 X104.278 Y102.402 E.45879
M73 P54 R1
G1 X104.278 Y102.909 E.01439
G1 X115.722 Y114.354 E.45879
G1 X115.722 Y114.861 E.01439
G1 X104.278 Y103.417 E.45879
G1 X104.278 Y103.924 E.01439
G1 X115.722 Y115.369 E.45879
M73 P55 R1
G1 X115.722 Y115.876 E.01439
G1 X104.278 Y104.432 E.45879
G1 X104.278 Y104.939 E.01439
G1 X115.722 Y116.384 E.45879
M73 P55 R0
G1 X115.722 Y116.891 E.01439
G1 X104.278 Y105.447 E.45879
M73 P56 R0
G1 X104.278 Y105.954 E.01439
G1 X115.722 Y117.399 E.45879
G1 X115.722 Y117.722 E.00917
G1 X115.538 Y117.722 E.00522
G1 X104.278 Y106.462 E.45142
G1 X104.278 Y106.969 E.01439
G1 X115.031 Y117.722 E.43108
M73 P57 R0
G1 X114.523 Y117.722 E.01439
G1 X104.278 Y107.477 E.41073
G1 X104.278 Y107.984 E.01439
G1 X114.016 Y117.722 E.39039
G1 X113.508 Y117.722 E.01439
G1 X104.278 Y108.492 E.37004
M73 P58 R0
G1 X104.278 Y108.999 E.01439
G1 X113.001 Y117.722 E.3497
G1 X112.494 Y117.722 E.01439
G1 X104.278 Y109.506 E.32936
G1 X104.278 Y110.014 E.01439
G1 X111.986 Y117.722 E.30901
M73 P59 R0
G1 X111.479 Y117.722 E.01439
G1 X104.278 Y110.521 E.28867
G1 X104.278 Y111.029 E.01439
G1 X110.971 Y117.722 E.26832
G1 X110.464 Y117.722 E.01439
G1 X104.278 Y111.536 E.24798
G1 X104.278 Y112.044 E.01439
G1 X109.956 Y117.722 E.22764
G1 X109.449 Y117.722 E.01439
M73 P60 R0
G1 X104.278 Y112.551 E.20729
G1 X104.278 Y113.059 E.01439
G1 X108.941 Y117.722 E.18695
G1 X108.434 Y117.722 E.01439
G1 X104.278 Y113.566 E.16661
G1 X104.278 Y114.074 E.01439
G1 X107.926 Y117.722 E.14626
G1 X107.419 Y117.722 E.01439
G1 X104.278 Y114.581 E.12592
G1 X104.278 Y115.089 E.01439
G1 X106.911 Y117.722 E.10557
G1 X106.404 Y117.722 E.01439
G1 X104.278 Y115.596 E.08523
M73 P61 R0
G1 X104.278 Y116.104 E.01439
G1 X105.896 Y117.722 E.06489
G1 X105.389 Y117.722 E.01439
G1 X104.278 Y116.611 E.04454
G1 X104.278 Y117.119 E.01439
G1 X105.042 Y117.883 E.03064
; stop printing object square-BodyPad.stl id:0 copy 0
M106 S163
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.8
G92 E0

G1 E-3.5 F3600
;WIPE_START
G1 F2400
G1 X104.335 Y117.176 E-1.5
;WIPE_END
EXCLUDE_OBJECT_END NAME=square-BodyPad.stl_id_0_copy_0
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object square-BodyPad.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=square-BodyPad.stl_id_0_copy_0
G1 Z1 F9000
G1 X116.011 Y118.011 Z1
G1 Z.8
G1 E5 F2400
;TYPE:Inner wall
;WIDTH:0.449999
G1 X103.989 Y118.011 E.38657
M73 P62 R0
G1 X103.989 Y101.989 E.5152
G1 X116.011 Y101.989 E.38657
G1 X116.011 Y117.971 E.51391
M73 P63 R0
G1 X116.418 Y118.418 F9000
G1 F2400
G1 X103.582 Y118.418 E.41275
G1 X103.582 Y101.582 E.54138
G1 X116.418 Y101.582 E.41275
M73 P64 R0
G1 X116.418 Y118.378 E.54009
G1 X116.8 Y118.8 F9000
;TYPE:Outer wall
;WIDTH:0.399999
G1 F1500
G1 X103.2 Y118.8 E.38361
G1 X103.2 Y101.2 E.49644
M73 P65 R0
G1 X116.8 Y101.2 E.38361
G1 X116.8 Y118.76 E.49531
M73 P66 R0
G1 X115.157 Y117.883 F9000
;TYPE:Internal solid infill
;WIDTH:0.401766
G1 F2400
G1 X115.722 Y117.318 E.02265
G1 X115.722 Y116.811 E.01439
G1 X114.811 Y117.722 E.03655
G1 X114.303 Y117.722 E.01439
G1 X115.722 Y116.303 E.05689
G1 X115.722 Y115.796 E.01439
G1 X113.796 Y117.722 E.07724
G1 X113.288 Y117.722 E.01439
G1 X115.722 Y115.288 E.09758
G1 X115.722 Y114.781 E.01439
G1 X112.781 Y117.722 E.11792
G1 X112.273 Y117.722 E.01439
M73 P67 R0
G1 X115.722 Y114.273 E.13827
G1 X115.722 Y113.766 E.01439
G1 X111.766 Y117.722 E.15861
G1 X111.258 Y117.722 E.01439
G1 X115.722 Y113.258 E.17896
G1 X115.722 Y112.751 E.01439
G1 X110.751 Y117.722 E.1993
G1 X110.243 Y117.722 E.01439
G1 X115.722 Y112.243 E.21964
G1 X115.722 Y111.736 E.01439
G1 X109.736 Y117.722 E.23999
M73 P68 R0
G1 X109.228 Y117.722 E.01439
G1 X115.722 Y111.228 E.26033
G1 X115.722 Y110.721 E.01439
G1 X108.721 Y117.722 E.28067
G1 X108.213 Y117.722 E.01439
G1 X115.722 Y110.213 E.30102
G1 X115.722 Y109.706 E.01439
G1 X107.706 Y117.722 E.32136
M73 P69 R0
G1 X107.198 Y117.722 E.01439
G1 X115.722 Y109.198 E.34171
G1 X115.722 Y108.691 E.01439
G1 X106.691 Y117.722 E.36205
G1 X106.183 Y117.722 E.01439
G1 X115.722 Y108.183 E.38239
G1 X115.722 Y107.676 E.01439
M73 P70 R0
G1 X105.676 Y117.722 E.40274
G1 X105.168 Y117.722 E.01439
G1 X115.722 Y107.168 E.42308
G1 X115.722 Y106.661 E.01439
G1 X104.661 Y117.722 E.44343
M73 P71 R0
G1 X104.278 Y117.722 E.01087
G1 X104.278 Y117.598 E.00352
G1 X115.722 Y106.154 E.45879
G1 X115.722 Y105.646 E.01439
G1 X104.278 Y117.091 E.45879
G1 X104.278 Y116.583 E.01439
G1 X115.722 Y105.139 E.45879
M73 P72 R0
G1 X115.722 Y104.631 E.01439
G1 X104.278 Y116.076 E.45879
G1 X104.278 Y115.568 E.01439
G1 X115.722 Y104.124 E.45879
G1 X115.722 Y103.616 E.01439
G1 X104.278 Y115.061 E.45879
M73 P73 R0
G1 X104.278 Y114.553 E.01439
G1 X115.722 Y103.109 E.45879
G1 X115.722 Y102.601 E.01439
G1 X104.278 Y114.046 E.45879
G1 X104.278 Y113.538 E.01439
G1 X115.538 Y102.278 E.45142
M73 P74 R0
G1 X115.031 Y102.278 E.01439
G1 X104.278 Y113.031 E.43108
G1 X104.278 Y112.523 E.01439
G1 X114.523 Y102.278 E.41073
G1 X114.016 Y102.278 E.01439
G1 X104.278 Y112.016 E.39039
M73 P75 R0
G1 X104.278 Y111.508 E.01439
G1 X113.508 Y102.278 E.37004
G1 X113.001 Y102.278 E.01439
G1 X104.278 Y111.001 E.3497
G1 X104.278 Y110.494 E.01439
G1 X112.494 Y102.278 E.32936
M73 P76 R0
G1 X111.986 Y102.278 E.01439
G1 X104.278 Y109.986 E.30901
G1 X104.278 Y109.479 E.01439
G1 X111.479 Y102.278 E.28867
G1 X110.971 Y102.278 E.01439
G1 X104.278 Y108.971 E.26832
G1 X104.278 Y108.464 E.01439
G1 X110.464 Y102.278 E.24798
M73 P77 R0
G1 X109.956 Y102.278 E.01439
G1 X104.278 Y107.956 E.22764
G1 X104.278 Y107.449 E.01439
G1 X109.449 Y102.278 E.20729
G1 X108.941 Y102.278 E.01439
G1 X104.278 Y106.941 E.18695
G1 X104.278 Y106.434 E.01439
G1 X108.434 Y102.278 E.16661
G1 X107.926 Y102.278 E.01439
G1 X104.278 Y105.926 E.14626
M73 P78 R0
G1 X104.278 Y105.419 E.01439
G1 X107.419 Y102.278 E.12592
G1 X106.911 Y102.278 E.01439
G1 X104.278 Y104.911 E.10557
G1 X104.278 Y104.404 E.01439
G1 X106.404 Y102.278 E.08523
G1 X105.896 Y102.278 E.01439
G1 X104.278 Y103.896 E.06489
G1 X104.278 Y103.389 E.01439
G1 X105.389 Y102.278 E.04454
G1 X104.881 Y102.278 E.01439
G1 X104.117 Y103.042 E.03064
G1 X115.744 Y102.416 F9000
;TYPE:Gap infill
;WIDTH:0.114511
G1 F1800
G1 X115.778 Y102.308 E.00064
G1 X115.755 Y102.193 E.00067
G1 X104.381 Y102.323 F9000
;TYPE:Internal solid infill
;WIDTH:0.38292
M73 P79 R0
G1 F2400
G1 X104.317 Y102.36 E.00198
G1 X104.382 Y102.394 E.00198
; stop printing object square-BodyPad.stl id:0 copy 0
M106 S132
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1
G92 E0

G1 E-4.7791 F3600
;WIPE_START
G1 F2400
G1 X104.317 Y102.36 E-.11048
G1 X104.381 Y102.323 E-.11042
;WIPE_END
EXCLUDE_OBJECT_END NAME=square-BodyPad.stl_id_0_copy_0
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object square-BodyPad.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=square-BodyPad.stl_id_0_copy_0
G1 Z1.2 F9000
G1 X116.011 Y118.011 Z1.2
G1 Z1
G1 E5 F2400
;TYPE:Inner wall
;WIDTH:0.449999
G1 X103.989 Y118.011 E.38657
G1 X103.989 Y101.989 E.5152
M73 P80 R0
G1 X116.011 Y101.989 E.38657
G1 X116.011 Y117.971 E.51391
G1 X116.418 Y118.418 F9000
G1 F2400
G1 X103.582 Y118.418 E.41275
M73 P81 R0
G1 X103.582 Y101.582 E.54138
G1 X116.418 Y101.582 E.41275
G1 X116.418 Y118.378 E.54009
M73 P82 R0
G1 X116.8 Y118.8 F9000
;TYPE:Outer wall
;WIDTH:0.399999
G1 F1500
G1 X103.2 Y118.8 E.38361
G1 X103.2 Y101.2 E.49644
M73 P83 R0
G1 X116.8 Y101.2 E.38361
G1 X116.8 Y118.76 E.49531
M73 P84 R0
G1 E-3.5 F3600
;WIPE_START
G1 F1500
G1 X115.8 Y118.763 E-1.5
;WIPE_END
G1 Z1.4 F9000
G1 X115.883 Y102.848 Z1.4
G1 Z1
G1 E5 F2400
;TYPE:Top surface
;WIDTH:0.404378
G1 F1800
G1 X115.313 Y102.278 E.02303
G1 X114.801 Y102.278 E.0146
G1 X115.722 Y103.199 E.03719
G1 X115.722 Y103.71 E.0146
G1 X114.29 Y102.278 E.05783
G1 X113.779 Y102.278 E.0146
G1 X115.722 Y104.221 E.07847
M73 P85 R0
G1 X115.722 Y104.732 E.0146
G1 X113.268 Y102.278 E.09911
G1 X112.757 Y102.278 E.0146
G1 X115.722 Y105.243 E.11975
G1 X115.722 Y105.754 E.0146
G1 X112.246 Y102.278 E.14039
G1 X111.734 Y102.278 E.0146
G1 X115.722 Y106.266 E.16103
G1 X115.722 Y106.777 E.0146
G1 X111.223 Y102.278 E.18167
G1 X110.712 Y102.278 E.0146
G1 X115.722 Y107.288 E.20232
M73 P86 R0
G1 X115.722 Y107.799 E.0146
G1 X110.201 Y102.278 E.22296
G1 X109.69 Y102.278 E.0146
G1 X115.722 Y108.31 E.2436
G1 X115.722 Y108.822 E.0146
G1 X109.178 Y102.278 E.26424
G1 X108.667 Y102.278 E.0146
G1 X115.722 Y109.333 E.28488
M73 P87 R0
G1 X115.722 Y109.844 E.0146
G1 X108.156 Y102.278 E.30552
G1 X107.645 Y102.278 E.0146
G1 X115.722 Y110.355 E.32616
G1 X115.722 Y110.866 E.0146
G1 X107.134 Y102.278 E.3468
M73 P88 R0
G1 X106.623 Y102.278 E.0146
G1 X115.722 Y111.377 E.36745
G1 X115.722 Y111.889 E.0146
G1 X106.111 Y102.278 E.38809
G1 X105.6 Y102.278 E.0146
G1 X115.722 Y112.4 E.40873
M73 P89 R0
G1 X115.722 Y112.911 E.0146
G1 X105.089 Y102.278 E.42937
G1 X104.578 Y102.278 E.0146
G1 X115.722 Y113.422 E.45001
M73 P90 R0
G1 X115.722 Y113.933 E.0146
G1 X104.278 Y102.489 E.46213
G1 X104.278 Y103 E.0146
G1 X115.722 Y114.444 E.46213
M73 P91 R0
G1 X115.722 Y114.956 E.0146
G1 X104.278 Y103.511 E.46213
G1 X104.278 Y104.022 E.0146
G1 X115.722 Y115.467 E.46213
G1 X115.722 Y115.978 E.0146
M73 P92 R0
G1 X104.278 Y104.533 E.46213
G1 X104.278 Y105.044 E.0146
G1 X115.722 Y116.489 E.46213
G1 X115.722 Y117 E.0146
G1 X104.278 Y105.556 E.46213
M73 P93 R0
G1 X104.278 Y106.067 E.0146
G1 X115.722 Y117.512 E.46213
G1 X115.722 Y117.722 E.00602
G1 X115.422 Y117.722 E.00858
G1 X104.278 Y106.578 E.45001
M73 P94 R0
G1 X104.278 Y107.089 E.0146
G1 X114.911 Y117.722 E.42937
G1 X114.4 Y117.722 E.0146
G1 X104.278 Y107.6 E.40872
M73 P95 R0
G1 X104.278 Y108.111 E.0146
G1 X113.889 Y117.722 E.38808
G1 X113.377 Y117.722 E.0146
G1 X104.278 Y108.623 E.36744
G1 X104.278 Y109.134 E.0146
G1 X112.866 Y117.722 E.3468
M73 P96 R0
G1 X112.355 Y117.722 E.0146
G1 X104.278 Y109.645 E.32616
G1 X104.278 Y110.156 E.0146
G1 X111.844 Y117.722 E.30552
G1 X111.333 Y117.722 E.0146
G1 X104.278 Y110.667 E.28488
M73 P97 R0
G1 X104.278 Y111.179 E.0146
G1 X110.821 Y117.722 E.26424
G1 X110.31 Y117.722 E.0146
G1 X104.278 Y111.69 E.2436
G1 X104.278 Y112.201 E.0146
G1 X109.799 Y117.722 E.22295
G1 X109.288 Y117.722 E.0146
G1 X104.278 Y112.712 E.20231
M73 P98 R0
G1 X104.278 Y113.223 E.0146
G1 X108.777 Y117.722 E.18167
G1 X108.266 Y117.722 E.0146
G1 X104.278 Y113.734 E.16103
G1 X104.278 Y114.246 E.0146
G1 X107.754 Y117.722 E.14039
G1 X107.243 Y117.722 E.0146
G1 X104.278 Y114.757 E.11975
G1 X104.278 Y115.268 E.0146
G1 X106.732 Y117.722 E.09911
G1 X106.221 Y117.722 E.0146
G1 X104.278 Y115.779 E.07847
M73 P99 R0
G1 X104.278 Y116.29 E.0146
G1 X105.71 Y117.722 E.05783
G1 X105.198 Y117.722 E.0146
G1 X104.278 Y116.802 E.03718
G1 X104.278 Y117.313 E.0146
G1 X104.848 Y117.883 E.02303
G1 E-3.5 F3600
;WIPE_START
G1 F1800
G1 X104.278 Y117.313 E-1.20996
G1 X104.278 Y117.119 E-.29004
;WIPE_END
G1 Z1.4 F9000
G1 X104.366 Y102.316 Z1.4
G1 Z1
G1 E5 F2400
;TYPE:Gap infill
;WIDTH:0.129542
G1 F1800
G1 X104.348 Y102.239 E.00054
G1 X104.193 Y102.258 E.00107
; stop printing object square-BodyPad.stl id:0 copy 0
G1 E-4.52779 F3600
;WIPE_START
G1 F1800
G1 X104.348 Y102.239 E-.31354
G1 X104.366 Y102.316 E-.15867
;WIPE_END
EXCLUDE_OBJECT_END NAME=square-BodyPad.stl_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
END_PRINT
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 95.94
; filament used [cm3] = 0.23
; filament used [g] = 0.29
; filament cost = 0.01; total filament used [g] = 0.29
; total filament cost = 0.01
; total layers count = 5
; estimated printing time (normal mode) = 2m 14s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; additional_cooling_fan_speed = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 25
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600 ;color change
; close_fan_the_first_x_layers = 3
; complete_print_exhaust_fan_speed = 80
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 500
; default_filament_colour = #1C71D8
; default_filament_profile = "Creality Generic PLA"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @Creality Ender3V2
; deretraction_speed = 40
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = enable_support;exclude_object;support_type;default_filament_colour;filament_cost;reduce_fan_stop_start_freq;change_filament_gcode;gcode_flavor;machine_end_gcode;machine_start_gcode;nozzle_type;print_host
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 1
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 34
; extruder_clearance_height_to_rod = 34
; extruder_clearance_radius = 47
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 30
; fan_kickstart = 0
; fan_max_speed = 90
; fan_min_speed = 40
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #1C71D8
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 18
; filament_density = 1.27
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.95
; filament_ids = GFG99
; filament_is_support = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 10
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Creality Generic PETG - Copy"
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_toolchange_delay = 0
; filament_type = PETG
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = everywhere
; gap_infill_speed = 30
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 80
; hot_plate_temp_initial_layer = 80
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 23%
; inherits_group = "0.20mm Standard @Creality Ender3V2";"Creality Generic PETG";"Creality Ender-3 V2 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 20
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 15
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 500
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 40
; interface_shells = 0
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.4
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 40
; ironing_angle = -1
; ironing_flow = 15%
; ironing_pattern = zig-zag
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.4
; machine_end_gcode = END_PRINT
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 500,500
; machine_max_acceleration_retracting = 1000,1000
; machine_max_acceleration_travel = 500,500
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 500,500
; machine_max_jerk_e = 5,5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_max_speed_e = 60,60
; machine_max_speed_x = 500,500
; machine_max_speed_y = 500,500
; machine_max_speed_z = 10,10
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M25 ;pause print
; machine_start_gcode = M117 ; clear display for KAMP meshing\nSTART_PRINT BED_TEMP={first_layer_bed_temperature[0]} EXTRUDER_TEMP={first_layer_temperature[0]}
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 255
; nozzle_temperature_initial_layer = 255
; nozzle_temperature_range_high = 270
; nozzle_temperature_range_low = 220
; nozzle_type = brass
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 500
; outer_wall_jerk = 9
; outer_wall_line_width = 0.4
; outer_wall_speed = 25
; overhang_1_4_speed = 0
; overhang_2_4_speed = 20
; overhang_3_4_speed = 15
; overhang_4_4_speed = 10
; overhang_fan_speed = 90
; overhang_fan_threshold = 25%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; post_process = 
; precise_outer_wall = 0
; preferred_orientation = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Creality Ender-3 V2 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Creality Ender3V2 - Copy
; printable_area = 0x0,220x0,220x220,0x220
; printable_height = 250
; printer_model = Creality Ender-3 V2
; printer_notes = 
; printer_settings_id = Creality Ender-3 V2 0.4 nozzle - Copy
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 0
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_length = 5
; retraction_minimum_travel = 2
; retraction_speed = 60
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = grid
; sparse_infill_speed = 50
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 0
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 0
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.4
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_top_z_distance = 0.2
; support_type = tree(manual)
; temperature_vitrification = 80
; template_custom_gcode = 
; textured_plate_temp = 80
; textured_plate_temp_initial_layer = 80
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 300x300
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_shell_layers = 4
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 500
; top_surface_jerk = 9
; top_surface_line_width = 0.4
; top_surface_pattern = monotonic
; top_surface_speed = 30
; travel_acceleration = 700
; travel_jerk = 12
; travel_speed = 150
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 3
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_y = 250.000
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 80
; bed_shape = 0x0,220x0,220x220,0x220
; first_layer_temperature = 255
; first_layer_height = 0.200
; CONFIG_BLOCK_END


